tap "homebrew/cask-versions"

brew "asdf"
brew "atuin"
brew "bash"
brew "bat"
brew "curl"
brew "exa"
brew "fd"
brew "fzf"
brew "git"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "mackup"
brew "mas" # mas-cli, to install from the App Store
brew "psgrep"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tig"
brew "tmux"
brew "zsh"

cask "1password7"
cask "alfred"
cask "dropbox"
cask "intellij-idea-ce"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "zoom"

brew "mas" # mas-cli, to install from the App Store
mas "Little Snitch Mini", id: 1629008763
mas "Things 3", id: 904280696
